### ISSUE TITLE
Animations on the article page are missing a frame

### ISSUE THREAD

**Issue by SKDemon820** [eliot-akira/neko#3]
I found your article about the history of Neko, and was saving the images from the `Icon Library` section so I could use some of the skins.  But I noticed that each skin only had 31 frames instead of the correct 32.  Towards the end of the animation right before the yawn, it turns out that the "licking" frame (the one where it tilts its head sideways and raises its paw) is instead replaying the still frame.  So instead of having the correct 32 images, there is only 31 images since "still" is included twice.

**Comment by eliot-akira** [comment]
Oh, nice catch! Thanks for letting me know about the missing frame. I'll look into solving it.

**Comment by eliot-akira** [comment]
So, I thought this was a simple mistake in the logic of displaying each Neko variant. But it turns out that the issue is in the collection: many of the variants have 31 instead of 32 images. They're missing the "wash" frame. Then I found that their originals have an extra "lickpaw" frame, which wasn't getting converted because it wasn't on the list of known actions.

I've regenerated the icon images, so the article page shows 32 frames for all variants.

https://eliotakira.com/neko/#icon-library

I made the page layout wider, the thumbnails larger, and to show random action from each variant so the overview is more lively.

In addition, I decided to include the whole collection in this Git repository.

https://github.com/eliot-akira/neko/tree/main/2023-icon-library

Enjoy! If you make something cool, I'd love to hear about it. :)
